### ISSUE TITLE
Error: Cannot find module 'unist-util-stringify-position'

### ISSUE THREAD

**Issue by rwwagner90** [rwjblue/create-rwjblue-release-it-setup#174]
Running `yarn create rwjblue-release-it-setup` is throwing an error for me:

```
success Installed "create-rwjblue-release-it-setup@3.1.1" with binaries:
      - create-rwjblue-release-it-setup
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'unist-util-stringify-position'
Require stack:
- /Users/rwwagner90/.config/yarn/global/node_modules/mdast-util-from-markdown/dist/index.js
- /Users/rwwagner90/.config/yarn/global/node_modules/mdast-util-from-markdown/index.js
- /Users/rwwagner90/.config/yarn/global/node_modules/create-rwjblue-release-it-setup/bin/rwjblue-release-it-setup.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/rwwagner90/.config/yarn/global/node_modules/mdast-util-from-markdown/dist/index.js:16:25)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/rwwagner90/.config/yarn/global/node_modules/mdast-util-from-markdown/dist/index.js',
    '/Users/rwwagner90/.config/yarn/global/node_modules/mdast-util-from-markdown/index.js',
    '/Users/rwwagner90/.config/yarn/global/node_modules/create-rwjblue-release-it-setup/bin/rwjblue-release-it-setup.js'
  ]
}
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-rwjblue-release-it-setup
Arguments: --labels-only
Directory: /Users/rwwagner90/shipshape/ember-array-utils
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by rwwagner90** [comment]
@rwjblue any ideas on this?
